apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sn-notifications-operator
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sn-notifications-operator
subjects:
  - kind: ServiceAccount
    name: k8sn-notifications-operator
    namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: k8sn-notifications-operator
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: k8sn-notifications-operator
  name: k8sn-notifications-operator
  namespace: openshift-operators