apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: k8sn-notifications-operator
  name: k8sn-notifications-operator
  namespace: openshift-operators
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: k8sn-notifications-operator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: k8sn-notifications-operator
  name: k8sn-notifications-operator
  namespace: openshift-operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8sn-notifications-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8sn-notifications-operator
    spec:
      imagePullSecrets:
      - name: regcred
      serviceAccount: k8sn-notifications-operator
      containers:
      - name: k8sn-notifications-operator
        imagePullPolicy: Always
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/vnoperatorscatalog/k8sn-notifications-operator:3.0.0
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
         
